### ISSUE TITLE
Option pricing example 

### ISSUE THREAD

**Issue by andrewcz** [RudyMorel/shadowing#1]
@RudyMorel are you able to give a brief example or code snippet for an option pricing example

**Comment by RudyMorel** [comment]
Dear @andrewcz, I will add more scripts with examples in the coming days

**Comment by andrewcz** [comment]
@RudyMorel cheers! Much appreciated

**Comment by RudyMorel** [comment]
Hi @andrewcz,
I apologize for the delay. 
I uploaded [tutorial.ipynb](https://github.com/RudyMorel/shadowing/blob/main/tutorial.ipynb) which provides the basics on how to use PathShadowing as well as option pricing
Thanks

**Comment by andrewcz** [comment]
Thank you Rudy! Much appreciated.
I consider this issue now closed.

Keep doing the amazing work your doing!
Have a great week.
Andrew
