### ISSUE TITLE
Path shadowing - more complex path

### ISSUE THREAD

**Issue by andrewcz** [RudyMorel/shadowing#3]
Hi @RudyMorel thank you for your continued work on this.
Just out of curiosity are you going to add to the example, a situation where a more complex simulation is used. For instance using your below package -
https://github.com/RudyMorel/scattering_spectra

- on another note, could this strategy be used to price quanto options. 

Kind regards ,
Andrew

**Comment by RudyMorel** [comment]
Hi @andrewcz,
This is indeed the plan in the coming weeks
- either providing the dataset of generated trajectories from SP500
- or providing the code to obtain such dataset
Thanks

**Comment by andrewcz** [comment]
Thank you @RudyMorel much appreciated!

**Comment by RudyMorel** [comment]
The new release of the code now contains a script `generate_snp.py` to precisely generate the dataset used for path shadowing. 
Sorry for the delay @andrewcz

**Comment by andrewcz** [comment]
Bless you ! Cheers Rudy!
